### ISSUE TITLE
Errors in python script

### ISSUE THREAD

**Issue by finlaywashere** [QuantumTCode/FIRST-MLWorkshop#2]
Error:

`CRITICAL:tensorflow:Label power cube first has no images in the category validation.

Traceback (most recent call last):

  File "C:\Users\finma\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "C:\Users\finma\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "C:\Users\finma\Desktop\ML\FIRST-MLWorkshop - Copy\scripts\retrain.py", line 1328, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)

  File "C:\Users\finma\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))

  File "C:\Users\finma\Desktop\ML\FIRST-MLWorkshop - Copy\scripts\retrain.py", line 1092, in main
    FLAGS.architecture))

  File "C:\Users\finma\Desktop\ML\FIRST-MLWorkshop - Copy\scripts\retrain.py", line 527, in get_random_cached_bottlenecks
    image_dir, category)

  File "C:\Users\finma\Desktop\ML\FIRST-MLWorkshop - Copy\scripts\retrain.py", line 234, in get_image_path
    mod_index = index % len(category_list)

ZeroDivisionError: integer division or modulo by zero`

I manually copied the image files in btw

**Comment by rsammelson** [comment]
How many images did you copy for each category?

**Comment by neild0** [comment]
Yeah, this error usually shows up when you have less than 30 images in a category. The algorithm requires a training, validation, and testing directory, so make sure that you have more than 30 images in each image class.

**Comment by finlaywashere** [comment]
I have 200 images in each category

**Comment by neild0** [comment]
What is your directory structure for the downloads folder? Specifically: power cube first?

**Comment by finlaywashere** [comment]
![capture1](https://user-images.githubusercontent.com/18103614/39500445-7db7756e-4d82-11e8-996f-0082df50bb15.PNG)
![capture2](https://user-images.githubusercontent.com/18103614/39500446-7dca5b02-4d82-11e8-91a8-76cd7da050d6.PNG)

**Comment by neild0** [comment]
Could you send a screenshot of your bottlenecks folder for power cube first? Is that screenshot the images in power cube first?

**Comment by finlaywashere** [comment]
That is a screenshot of the power cube first folder, I'll post a screenshot of the bottlenecks when I get home tn.

**Comment by finlaywashere** [comment]
![capture1](https://user-images.githubusercontent.com/18103614/39542731-4f160bf4-4e17-11e8-81b4-09a947f6ca5d.PNG)

**Comment by finlaywashere** [comment]
Nvm i fixed it, it was the file names because i manually added them

**Comment by finlaywashere** [comment]
One other question. what is the name of the input operation you use for this? What i mean by that is what do i feed the image data into from java? Like using this code 
`s.runner().feed("DecodeJpeg/contents", image)`
